### ISSUE TITLE
Used to stream the status of fabric?

### ISSUE THREAD

**Issue by rafaelcapucho** [jonathanslenders/pypager#1]
Hello!,

It isn't an issue but a question, 

I need to execute some Fabric commands in one web app and show the results of the execution in the Dashboard (Web), it is working but I need to wait until `subprocess.check_output` finish to have the result back.

I would like to streaming the output of Fabric as soon as it is printed in the subprocess, and in the other hand, send it back to webapp buffering too.

Could pypager help me in any step? If not, do you know some way to do it?

Today I use this code to call a new Fabric process:

```
def exec_command(list_commands):

    abs_file = os.path.abspath(__file__)

    up = os.path.dirname(abs_file)
    up = os.path.dirname(up)

    manager_path = '{0}/manager'.format(up)

    results = subprocess.check_output(list_commands, cwd=manager_path)

    return results.decode('utf-8').strip().split("\n")
```

And that is the way I get the result back and send to the dashboard:

```
@manager_app.route('/git.pull/<worker_ip:re:[\.0-9]+>\:<worker_port:int>', method='GET')
@auth_basic(check_pass)
def git_pull_worker(worker_ip, worker_port):

    bottle.response.content_type = 'application/json'

    results = exec_command(['/usr/local/bin/fab', "git.pull:hosts={ip}".format(ip=worker_ip)])

    return {
        'worker_ip': worker_ip,
        'worker_port': worker_port,
        'results': results
    }
```

Thank you

**Comment by jonathanslenders** [comment]
Hi @rafaelcapucho,

Pypager would not help with this. It's made for displaying a stream in a terminal, not in a web application.

This is not an easy thing to do. First, you need to have a web socket connection to the client in order to stream data. There are various Python libraries doing that. Secondly, instead of calling subprocess.check_output, it's better to use subprocess.stdout.read(), probably preceded by select.select() to read chunks of output and send it to the web socket.

**Comment by rafaelcapucho** [comment]
Hello @jonathanslenders,

Thank you very much for your answer and for targeting me the right path.. 

I will clode the Issue, best regards.
