### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'strike'

### ISSUE THREAD

**Issue by avatar-lavventura** [jonathanslenders/pypager#20]
I am having following error:

```
Traceback (most recent call last):
  File "/home/alper/venv/bin/pypager", line 8, in <module>
    sys.exit(run())
  File "/home/alper/venv/lib/python3.8/site-packages/pypager/entry_points/run_pypager.py", line 21, in run
    pager = Pager.from_pipe()
  File "/home/alper/venv/lib/python3.8/site-packages/pypager/pager.py", line 152, in from_pipe
    self.add_source(PipeSource(fileno=sys.stdin.fileno(), lexer=lexer))
  File "/home/alper/venv/lib/python3.8/site-packages/pypager/source.py", line 86, in __init__
    self._attrs = Attrs(
TypeError: __new__() missing 1 required positional argument: 'strike'
```

How can I resolve it?

**Comment by davidcardonAH** [comment]
It looks like prompt toolkit v.3.0.20 introduced a breaking API change to its Attrs NamedTuple: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/3.0.20/prompt_toolkit/styles/base.py#L26, which does not support backward compatible construction for any of its clients (of which, `pypager` is one)

Since `Attrs` is constructed directly in `pypager`, one possible workaround would be to patch `pypager.source.Attrs` back to its original (i.e., exclude the "strike" name).:

```python
from pypager import source
source.Attrs = NamedTuple(
    "Attrs",
    [
        ("color", Optional[str]),
        ("bgcolor", Optional[str]),
        ("bold", Optional[bool]),
        ("underline", Optional[bool]),
        ("italic", Optional[bool]),
        ("blink", Optional[bool]),
        ("reverse", Optional[bool]),
        ("hidden", Optional[bool]),
    ],
)

pipe_source = source.PipeSource(file_descriptor)
```

  I'm not sure if that doesn't have other side-effects. Possibly the better way to handle this would be to PR a change to [the `Attrs(...)` constructor call in pypager's `source.py` file](https://github.com/prompt-toolkit/pypager/blob/master/pypager/source.py#L91-L100).

**Comment by avatar-lavventura** [comment]
@davidcardonAH Thanks
